// import { IconsType } from "../@types/player.model";

// export const defaultIcons: IconsType = {
//   setting: <SettingIcon />,
//   checkMark: <CheckMark />,
//   arrow: <ArrowRight />,
//   play: <PlayIcon />,
//   pause: <PauseIcon />,
//   volumeUp: <HighVolume />,
//   volumeDown: <LowVolume />,
//   mute: <MuteVolume />,
//   picInPic: <PictureInPicture />,
//   picOutPic: <PictureOutPicture />,
//   fullScreen: <FullScreenIcon />,
//   unFullScreen: <ExitFullScreenIcon />,
//   speed: <PlaybackSpeed />,
//   quality: <ChangeQuality />,
//   subtitle: <Subtitle />,
//   audioTrack: <AudioIcon />,
//   autoPlayOn: <AutoPlayOne />,
//   autoPlayOff: <AutoPlayOff />,
//   jumpBack: <JumpBack />,
//   jumpForward: <JumpForward />,
//   mic: <Mic />,
//   playArrow: <PlayArrow />,
// };
